#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yaml
Version  : 0.1.6
Release  : 6
URL      : http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz
Source0  : http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz
Summary  : Library to parse and emit YAML
Group    : Development/Tools
License  : MIT
Requires: yaml-lib
Patch1: cve-2014-9130.patch

%description
LibYAML - A C library for parsing and emitting YAML.
To build and install the library, run:
$ ./configure
$ make
# make install

%package dev
Summary: dev components for the yaml package.
Group: Development
Requires: yaml-lib

%description dev
dev components for the yaml package.


%package lib
Summary: lib components for the yaml package.
Group: Libraries

%description lib
lib components for the yaml package.


%prep
%setup -q -n yaml-0.1.6
%patch1 -p1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
