#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yaml
Version  : 0.1.7
Release  : 14
URL      : http://pyyaml.org/download/libyaml/yaml-0.1.7.tar.gz
Source0  : http://pyyaml.org/download/libyaml/yaml-0.1.7.tar.gz
Summary  : Library to parse and emit YAML
Group    : Development/Tools
License  : MIT
Requires: yaml-lib

%description
LibYAML - A C library for parsing and emitting YAML.
To build and install the library, run:
$ ./configure
$ make
# make install

%package dev
Summary: dev components for the yaml package.
Group: Development
Requires: yaml-lib
Provides: yaml-devel

%description dev
dev components for the yaml package.


%package lib
Summary: lib components for the yaml package.
Group: Libraries

%description lib
lib components for the yaml package.


%prep
%setup -q -n yaml-0.1.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517696852
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1517696852
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libyaml.so
/usr/lib64/pkgconfig/yaml-0.1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libyaml-0.so.2
/usr/lib64/libyaml-0.so.2.0.5
